// src/client/components/Profile/ProfileNav.tsx
import * as React from 'react';
import Link from '../Link';
import {observer, inject} from 'mobx-react';

import ProfileStore from '../../stores/ProfileStore';
import UserStore from '../../stores/UserStore';

import FollowStatus from './FollowStatus';

interface Props {
  title: string;
  profileStore?: ProfileStore;
  userStore?: UserStore;
}

@inject((allStores) => ({
  profileStore: allStores.profileStore as ProfileStore,
  userStore: allStores.userStore as UserStore,
})) @observer
export default class ProfileNav extends React.Component<Props, {}> {
  renderLink(url: string, label: string) {
    return (
      <Link to={url} activeClassName="active">
        {label}
      </Link>
    );
  }

  render() {
    const {name} = this.props.profileStore!;
    const isFollowing = this.props.userStore!.isFollowing(name);

    return (
      <div className="user-header">
        <div className="user-header-top">
          <h2>
            {this.props.title}
          </h2>

          <FollowStatus name={name} isFollowing={isFollowing} />
        </div>

        <div className="user-links">
          {this.renderLink(`/users/${name}`, 'Posts')}
          {' / '}
          {this.renderLink(`/users/${name}/liked`, 'Liked')}
          {' / '}
          {this.renderLink(`/users/${name}/followers`, 'Followers')}
          {' / '}
          {this.renderLink(`/users/${name}/following`, 'Following')}
        </div>
      </div>
    );
  }
}

// src/vue-client/components/ProfileNav.vue
<template>
  <div class="user-header">
    <div class="user-header-top">
      <h2>
        {{title}}
      </h2>
    </div>
    <div class="user-links">
      <router-link :to="`/users/${name}`" exact-active-class="active">
        Posts
      </router-link>
      /
      <router-link :to="`/users/${name}/liked`" active-class="active">
        Liked
      </router-link>
      /
      <router-link :to="`/users/${name}/following`" active-class="active">
        Following
      </router-link>
      /
      <router-link :to="`/users/${name}/followers`" active-class="active">
        Followers
      </router-link>
    </div>
  </div>
</template>

<script>
import {mapState} from 'vuex';

export default {
  props: ['title'],

  computed: {
    ...mapState({
      name: (state) => state.profile.user.twitterName,
    }),
  },
};
</script>
