// app/src/components/audio-player/AudioPlayer.vue
<template>
  <div class="audio-player">
    <div v-if="nowPlaying">
      <youtube v-if="nowPlaying.source === 'youtube'"
        :url="nowPlaying.youtubeUrl"
        :isPlaying="isPlaying"
        @ended="this.handlePlaybackEnded">
      </youtube>
      <audio-stream v-if="nowPlaying.source === 'bandcamp'"
        :url="nowPlaying.bandcampStreamingUrl"
        :isPlaying="isPlaying"
        @ended="this.handlePlaybackEnded">
      </audio-stream>
      <audio-stream v-if="nowPlaying.source === 'soundcloud'"
        :url="nowPlaying.soundcloudStreamingUrl"
        :isPlaying="isPlaying"
        @ended="this.handlePlaybackEnded">
      </audio-stream>
    </div>

    <div class="audio-player--controls">
      <button class="play-pause-button" @click="handlePlayPauseClick"
        :disabled="!nowPlaying">
        <icon :glyph="playPauseIcon"></icon>
      </button>

      <button class="next-button" @click="handleNextClick"
        :disabled="!nowPlaying">
        <icon :glyph="nextIcon"></icon>
      </button>
    </div>

    <div class="audio-player--main">
      <div>{{title}}</div>
      <div>{{artist}}</div>

      <div v-if="nowPlaying">
        playing from
        <router-link :to="playbackSourcePath">{{playbackSourceLabel}}</router-link>
      </div>
    </div>

    <img v-if="nowPlaying && albumArt" :src="albumArt" class="audio-player--art">
    <icon v-else class="audio-player--art -placeholder"
      :glyph="albumPlaceholderIcon"></icon>
  </div>
</template>

<script>
import { mapState } from 'vuex';
import Icon from '../Icon.vue';

import Youtube from './Youtube.vue';
import AudioStream from './AudioStream.vue';

const playIcon = require('../../../assets/play.svg');
const pauseIcon = require('../../../assets/pause.svg');
const nextIcon = require('../../../assets/next.svg');
const albumPlaceholderIcon = require('../../../assets/record.svg');

export default {
  data() {
    return {
      playIcon,
      pauseIcon,
      nextIcon,
      albumPlaceholderIcon,
    };
  },

  computed: {
    ...mapState('playback', [
      'nowPlaying',
      'isPlaying',
      'playbackSourcePath',
      'playbackSourceLabel',
    ]),

    playPauseIcon() {
      return this.isPlaying ? pauseIcon : playIcon;
    },

    artist() {
      if (this.nowPlaying) {
        return this.nowPlaying.song.artists[0];
      } else {
        return null;
      }
    },

    title() {
      if (this.nowPlaying) {
        return this.nowPlaying.song.title;
      } else {
        return '(nothing playing)';
      }
    },

    albumArt() {
      if (this.nowPlaying) {
        return this.nowPlaying.song.albumArt;
      } else {
        return null;
      }
    },

    embedProps() {
      return {
        isPlaying: this.isPlaying,
        'v-on:ended': this.handlePlaybackEnded,
      };
    },
  },

  methods: {
    handlePlayPauseClick() {
      this.$store.dispatch('playback/togglePlayback');
    },
    handleNextClick() {},
    handlePlaybackEnded() {
      this.$store.dispatch('playback/clearPlayback');
    },
  },

  components: { Icon, Youtube, AudioStream },
};
</script>

// src/client/components/AudioPlayer/index.tsx
import * as React from 'react';
import {Link} from 'react-router';
import {inject, observer} from 'mobx-react';
import * as classNames from 'classnames';

import PlaybackStore from '../../stores/PlaybackStore';
import {PlaylistEntry} from '../../../universal/resources';
import serializeSongLabel from '../../util/serializeSongLabel';

import Youtube from './Youtube';
import AudioStream from './AudioStream';
import Icon from '../Icon';

const playIcon = require('../../../../assets/play.svg');
const pauseIcon = require('../../../../assets/pause.svg');
const nextIcon = require('../../../../assets/next.svg');
const albumPlaceholderIcon = require('../../../../assets/record.svg');

interface Props {
  playbackStore?: PlaybackStore;
}

@inject((allStores) => ({
  playbackStore: allStores.playbackStore as PlaybackStore,
})) @observer
export default class VideoPlayer extends React.Component<Props, {}> {
  handlePlayPauseClick() {
    this.props.playbackStore!.togglePlayback();
  }

  handleNextClick() {
    this.props.playbackStore!.nextSong();
  }

  handleSongEnd() {
    this.props.playbackStore!.nextSong();
  }

  renderPlaybackSource() {
    const {playbackSourcePath, playbackSourceLabel, nowPlaying} = this.props.playbackStore!;

    if (!nowPlaying) {
      return null;
    }

    return (
      <div>playing from <Link to={playbackSourcePath}>{playbackSourceLabel}</Link></div>
    );
  }

  renderArt() {
    const {nowPlaying} = this.props.playbackStore!;

    let art = null;

    if (nowPlaying && nowPlaying.song.albumArt) {
      art = nowPlaying.song.albumArt;
    }

    if (art) {
      return <img className="audio-player--art" src={art} />;
    } else {
      return <Icon className="audio-player--art -placeholder" glyph={albumPlaceholderIcon} />;
    }
  }

  renderEmbed() {
    const {nowPlaying, isPlaying} = this.props.playbackStore!;

    if (!nowPlaying) {
      return null;
    }

    const commonProps = {
      playing: isPlaying,
      onEnded: () => this.handleSongEnd()
    };

    if (nowPlaying.source === 'bandcamp') {
      return (
        <AudioStream url={nowPlaying.bandcampStreamingUrl} {...commonProps} />
      );

    } else if (nowPlaying.source === 'soundcloud') {
      return (
        <AudioStream url={nowPlaying.soundcloudStreamingUrl} {...commonProps} />
      );

    } else {
      return (
        <Youtube url={nowPlaying.youtubeUrl} {...commonProps} />
      );
    }
  }

  render() {
    const {nowPlaying, isPlaying} = this.props.playbackStore!;

    const artist = nowPlaying ? nowPlaying.song.artists.join(', ') : null;
    const title = nowPlaying ? nowPlaying.song.title : '(nothing playing)';

    const playPauseIcon = isPlaying ? pauseIcon : playIcon;

    return (
      <div className="audio-player">
        {this.renderEmbed()}

        <div className="audio-player--controls">
          <button className="play-pause-button" onClick={() => this.handlePlayPauseClick()}
            disabled={!nowPlaying}>
            <Icon glyph={playPauseIcon} />
          </button>

          <button className="next-button" onClick={() => this.handleNextClick()}
            disabled={!nowPlaying}>
            <Icon glyph={nextIcon} />
          </button>
        </div>

        <div className="audio-player--main">
          <div>{title}</div>
          <div>{artist}</div>

          {this.renderPlaybackSource()}
        </div>

        {this.renderArt()}
      </div>
    );
  }
}
