// src/client/components/AudioPlayer/AudioStream.tsx
import * as React from 'react';

interface Props {
  url: string;
  playing: boolean;
  onEnded: () => void;
}

export default class AudioStream extends React.Component<Props, {}> {
  player: HTMLAudioElement;

  componentDidMount() {
    this.player.addEventListener('ended', this.props.onEnded);
  }

  componentWillUnmount() {
    this.player.removeEventListener('ended', this.props.onEnded);
  }

  componentWillReceiveProps(nextProps: Props) {
    if (nextProps.playing && !this.props.playing) {
      this.player.play();
    }

    if (!nextProps.playing && this.props.playing) {
      this.player.pause();
    }
  }

  render() {
    const {url} = this.props;
    return <audio src={url} autoPlay ref={(el) => this.player = el} />;
  }
}

// app/src/components/audio-player/AudioStream.vue
<template>
  <audio :src="url" autoPlay ref="player"></audio>
</template>

<script>
export default {
  props: ['url', 'isPlaying'],

  mounted() {
    this.$refs.player.addEventListener('ended', this.handleEnded);
  },

  beforeDestroy() {
    this.$refs.player.removeEventListener('ended', this.handleEnded);
  },

  watch: {
    isPlaying(newVal) {
      if (newVal) {
        this.$refs.player.play();
      } else {
        this.$refs.player.pause();
      }
    },
  },

  methods: {
    handleEnded() {
      this.$emit('ended');
    },
  },
};
</script>
