// src/client/components/AddSongModal/ConfirmScreen.tsx
import * as React from 'react';
import {inject, observer} from 'mobx-react';

import SearchBox from './SearchBox';
import SearchResults from './SearchResults';

import AddSongStore from '../../stores/AddSongStore';
import UserStore from '../../stores/UserStore';
import serializeSongLabel from '../../util/serializeSongLabel';
import TwitterShareBox from './TwitterShareBox';

interface Props {
  addSongStore?: AddSongStore;
  userStore?: UserStore;
}

@inject((allStores) => ({
  addSongStore: allStores.addSongStore as AddSongStore,
})) @observer
class ConfirmScreen extends React.Component<Props, {}> {
  state = {
    crossPostEnabled: false,
    noteText: '',
  }

  handleToggleTwitter() {
    const crossPostEnabled = !this.state.crossPostEnabled;

    this.setState({
      crossPostEnabled,
    });

    if (!crossPostEnabled) {
      // remove the tweet if cross-post is disabled
      this.props.addSongStore!.updateTweetText(null);
    }
  }

  handleNoteChange(e: React.SyntheticEvent<HTMLTextAreaElement>) {
    const noteText = e.currentTarget.value;
    this.setState({noteText});
  }

  handleSubmit() {
    this.props.addSongStore!.addSong(this.state.noteText);
  }

  renderLabel() {
    const {manualArtist, manualTitle, manualEntry, selectedSong} = this.props.addSongStore!.txn;

    if (manualEntry) {
      return `${manualArtist} - ${manualTitle}`;
    } else {
      return serializeSongLabel(selectedSong!);
    }
  }

  render() {
    const song = this.props.addSongStore!.txn.selectedSong!;
    const {crossPostEnabled} = this.state;

    return (
      <div className="confirm-screen">
        <p>you're posting <strong>{this.renderLabel()}</strong></p>

        <div className="note-box">
          <textarea value={this.state.noteText} onChange={(e) => this.handleNoteChange(e)}
            placeholder="(optional) Write a note about this song!" />
        </div>

        <p>
          <label>
            <input type="checkbox"
              checked={crossPostEnabled}
              onChange={() => this.handleToggleTwitter()} />
            {' '} cross-post to twitter
          </label>
        </p>

        {this.state.crossPostEnabled ? <TwitterShareBox /> : null}

        <button onClick={() => this.handleSubmit()} className="submit" data-test="add-song-confirm">
          post it!!
        </button>
      </div>
    );
  }
}

export default ConfirmScreen;

// app/src/components/add-song-modal/ConfirmScreen.vue
<template>
  <div class="confirm-screen">
    <p>you're posting <strong>{{ songLabel }}</strong></p>

    <div class="note-box">
      <textarea v-model="noteText" placeholder="(optional) Write a note about this song!"/>
    </div>

    <p>
      <label>
        <input type="checkbox" v-model="twitterPostEnabled">
        cross-post to twitter
      </label>
    </p>

    <twitter-share-field v-if="twitterPostEnabled" v-model="tweetText"/>

    <button @click="handleSubmit" class="submit" data-test="add-song-confirm">
      post it!!
    </button>
  </div>
</template>

<script>
import { mapGetters, mapState } from 'vuex';

import serializeSongLabel from '../../util/serializeSongLabel';
import TwitterShareField from './TwitterShareField.vue';
import {
  getDefaultTweet,
  getTweetLength,
  TWEET_LENGTH,
} from '../../util/songTweet';

export default {
  components: { TwitterShareField },

  data() {
    return {
      noteText: '',
      tweetText: '',
      twitterPostEnabled: false,
    };
  },

  computed: {
    ...mapGetters(['addSongArtist', 'addSongTitle']),

    ...mapState({
      songLabel: (state) => {
        const {
          manualArtist,
          manualTitle,
          manualEntry,
          selectedSong,
        } = state.addSong;

        if (manualEntry) {
          return `${manualArtist} - ${manualTitle}`;
        } else {
          return serializeSongLabel(selectedSong);
        }
      },
    }),
  },

  mounted() {
    this.tweetText = getDefaultTweet(this.addSongArtist, this.addSongTitle);
  },

  methods: {
    handleSubmit(evt) {
      evt.preventDefault();

      const opts = {
        note: this.noteText === '' ? null : this.noteText,
      };

      if (this.twitterPostEnabled) {
        if (getTweetLength(this.tweetText) > TWEET_LENGTH) {
          alert('Yo your twitter message is too long');
          return;
        }

        opts.tweet = this.tweetText === '' ? null : this.tweetText;
      }

      this.$store.dispatch('submitSong', opts);
    },
  },
};
</script>
