// src/client/components/AddSongModal/ManualEntryForm.tsx
import * as React from 'react';
import {inject, observer} from 'mobx-react';

import AddSongStore from '../../stores/AddSongStore';

interface Props {
  addSongStore?: AddSongStore;
}

@inject((allStores) => ({
  addSongStore: allStores.addSongStore as AddSongStore,
})) @observer
export default class ManualEntryForm extends React.Component<Props, {}> {
  state = this.getDefaultState();

  getDefaultState() {
    const {manualEntrySuggestion} = this.props.addSongStore!.txn;

    return {
      artist: manualEntrySuggestion ? manualEntrySuggestion.artist : '',
      title: manualEntrySuggestion ? manualEntrySuggestion.title : '',
    };
  }

  handleChange(e: React.SyntheticEvent<HTMLInputElement>) {
    const {name, value} = e.currentTarget;

    this.setState({
      [name]: value,
    });
  }

  handleSubmit(e: React.FormEvent<any>) {
    e.preventDefault();

    this.props.addSongStore!.manualEntry(this.state.artist, this.state.title);
  }

  render() {
    const isFilled = this.state.artist !== '' && this.state.title !== '';

    return (
      <form className="submit-box" onSubmit={(e) => this.handleSubmit(e)}>
        <input type="text" placeholder="Artist"
          value={this.state.artist} name="artist"
          onChange={(e) => this.handleChange(e)} />

        <input type="text" placeholder="Title"
          value={this.state.title} name="title"
          onChange={(e) => this.handleChange(e)} />

        <button type="submit" disabled={!isFilled}>
          next
        </button>
      </form>
    );
  }
}

// app/src/components/add-song-modal/ManualEntryForm.vue
<template>
  <form class="submit-box" @submit="handleSubmit">
    <input type="text" name="artist" placeholder="Artist" v-model="artist" />
    <input type="text" name="title" placeholder="Title" v-model="title" />

    <button type="submit" :disabled="!isFilled">
      next
    </button>
  </form>
</template>

<script>
import { mapState } from 'vuex';

export default {
  data() {
    return {
      artist: '',
      title: '',
    };
  },

  computed: {
    isFilled() {
      return this.artist.length && this.title.length;
    },
    ...mapState({
      manualEntrySuggestion: (state) => state.addSong.manualEntrySuggestion,
    }),
  },

  mounted() {
    if (this.manualEntrySuggestion) {
      this.artist = this.manualEntrySuggestion.artist;
      this.title = this.manualEntrySuggestion.title;
    }
  },

  methods: {
    handleSubmit(evt) {
      evt.preventDefault();
      const { artist, title } = this;
      this.$store.dispatch('submitManualEntry', { artist, title });
    },
  },
};
</script>
