// src/client/components/AddSongModal/SearchScreen.tsx
import * as React from 'react';
import {inject, observer} from 'mobx-react';

import SearchBox from './SearchBox';
import SearchResults from './SearchResults';
import ManualEntryForm from './ManualEntryForm';

import AddSongStore from '../../stores/AddSongStore';

interface Props {
  addSongStore?: AddSongStore;
}

@inject((allStores) => ({
  addSongStore: allStores.addSongStore as AddSongStore,
})) @observer
class SearchScreen extends React.Component<Props, {}> {
  handleToggleManualEntry(e: React.SyntheticEvent<HTMLAnchorElement>) {
    e.preventDefault();

    this.props.addSongStore!.txn.manualEntry = !(this.props.addSongStore!.txn.manualEntry);
  }

  handleReturnToInitialScreen(e: React.SyntheticEvent<HTMLAnchorElement>) {
    e.preventDefault();

    this.props.addSongStore!.showAddSongScreen();
  }

  renderManualEntry() {
    return (
      <div>
        <ManualEntryForm />

        Or{' '}
        <a onClick={(e) => this.handleToggleManualEntry(e)} href="#">
          search for a song
        </a>
      </div>
    );
  }

  renderSearch() {
    return (
      <div>
        <p>
          To finish sharing, just search for the song title and artist that matches this video:
        </p>

        <SearchBox />

        <SearchResults />

        Or{' '}
        <a onClick={(e) => this.handleToggleManualEntry(e)} href="#" data-test="use-manual-entry">
          manually enter a title and artist
        </a>
      </div>
    );
  }

  renderNotEmbeddable() {
    const {shareTitle, shareSourceName} = this.props.addSongStore!.txn;

    return (
      <div>
        <p>
          You tried to share the video "{shareTitle}" via {shareSourceName}, but unfortunately, this video can't be embedded on Jam Buds due to restrictions set by the video's uploader.
        </p>
        <p>
          We recommend trying to find another video for this song!
        </p>
        <a onClick={(e) => this.handleReturnToInitialScreen(e)} href="#">
          Try again
        </a>
      </div>
    );
  }

  renderLoaded() {
    const {shareTitle, manualEntry, shareEmbeddable, shareSourceName} = this.props.addSongStore!.txn;

    if (!shareEmbeddable) {
      return this.renderNotEmbeddable();
    }

    return (
      <div>
        <p>
          You're sharing the video "{shareTitle}" via {shareSourceName}.
        </p>

        {manualEntry ? this.renderManualEntry() : this.renderSearch()}
      </div>
    );
  }

  render() {
    const {loadedShareLink} = this.props.addSongStore!.txn;

    return loadedShareLink ? this.renderLoaded() : <div>loading...</div>;
  }
}

export default SearchScreen;

// app/src/components/add-song-modal/SearchScreen.vue
<template>
  <div v-if="notEmbeddable">
    <p>
      You tried to share the song "{{shareTitle}}" via {{shareSourceName}}, but unfortunately, this song can't be embedded on Jam Buds due to restrictions set by the song's uploader.
    </p>
    <p>
      We recommend trying to find another source for this song!
    </p>
    <a @click="handleReturnToInitialScreen" href="#">
      Try again
    </a>
  </div>

  <div v-else>
    <p>
      You're sharing the link "{{shareTitle}}" via {{shareSourceName}}.
    </p>

    <div v-if="manualEntry">
      <manual-entry-form></manual-entry-form>

      Or
      <a @click="handleToggleManualEntry" href="#">
        search for a song
      </a>
    </div>

    <div v-else>
      <spotify-search></spotify-search>

      Or
      <a @click="handleToggleManualEntry" href="#" data-test="use-manual-entry">
        manually enter a title and artist
      </a>
    </div>
  </div>
</template>

<script>
import { mapState } from 'vuex';
import SpotifySearch from './SpotifySearch.vue';
import ManualEntryForm from './ManualEntryForm.vue';

export default {
  components: { SpotifySearch, ManualEntryForm },

  data() {
    return {};
  },

  computed: {
    ...mapState({
      shareTitle: (state) => state.addSong.shareTitle,
      shareSourceName: (state) => state.addSong.shareSourceName,
      notEmbeddable: (state) => !state.addSong.shareEmbeddable,
      manualEntry: (state) => state.addSong.manualEntry,
    }),
  },

  methods: {
    handleReturnToInitialScreen(evt) {
      evt.preventDefault();
      this.$store.dispatch('resetAddSong');
    },
    handleToggleManualEntry(evt) {
      evt.preventDefault();
      this.$store.dispatch('toggleAddSongManualEntry');
    },
  },
};
</script>
