// src/vue-client/components/playlist/Playlist.vue
<template>
  <div v-if="!entries.length" class="main-placeholder">
    <slot name="placeholder"></slot>
  </div>

  <div v-else>
    <ul class="playlist-entries">
      <li v-for="entry in entries" :key="entry.id">
        <entry-posted-by :entry="entry"></entry-posted-by>
        <playlist-entry
          :entry="entry"
          :playbackSourceLabel="playbackSourceLabel"
          :playbackSourcePath="playbackSourcePath">
        </playlist-entry>
      </li>
    </ul>

    <div v-if="!entriesExhausted">
      <div v-if="loadingNextPage">
        Loading...
      </div>

      <a v-else href="#" @click="handleRequestNextPage">
        Load next page
      </a>
    </div>
  </div>
</template>

<script>
  import EntryPostedBy from './EntryPostedBy.vue';
  import PlaylistEntry from './PlaylistEntry.vue';

  export default {
    props: [
      'entries', 'entriesExhausted', 'loadingNextPage', 'playbackSourceLabel', 'playbackSourcePath'
    ],

    components: {EntryPostedBy, PlaylistEntry},

    methods: {
      handleRequestNextPage(evt) {
        evt.preventDefault();
        this.$emit('requestNextPage');
      }
    }
  }
</script>

// src/client/components/Playlist/index.tsx
import * as React from 'react';
import {observer} from 'mobx-react';

import PlaylistItem from './PlaylistItem';

import PlaylistEntry from '../../stores/PlaylistEntry';
import PaginatedPlaylistEntriesList from '../../stores/PaginatedPlaylistEntriesList';

interface Props {
  entryList: PaginatedPlaylistEntriesList;
  noItemsPlaceholder: () => JSX.Element;
}

@observer
class Playlist extends React.Component<Props, {}> {
  handleGetNextPage(e: React.MouseEvent<any>) {
    e.preventDefault();
    this.props.entryList.getNextPage();
  }

  renderItems(items: PlaylistEntry[]) {
    if (items.length === 0) {
      return this.props.noItemsPlaceholder();
    }

    return (
      <ul className="playlist-entries">
        {items.map((track, idx) =>
          <li key={track.id}>
            <PlaylistItem
              track={track} trackIndex={idx}
              entryList={this.props.entryList} />
          </li>
        )}
      </ul>
    );
  }

  renderNextPageLoading() {
    const {nextPageRequest, loadedFirstPage, entriesExhausted} = this.props.entryList;

    if (!nextPageRequest) {
      if (entriesExhausted) {
        return null;
      }

      return (
        <a href="#" onClick={(e) => this.handleGetNextPage(e)}>
          Load next page
        </a>
      );
    }

    let className = '';
    if (!loadedFirstPage) {
      className = 'main-placeholder';
    }

    return nextPageRequest.case({
      pending: () => <div className={className}>Loading...</div>,
      rejected: () => <div className={className}>Error loading!</div>,
      fulfilled: () => <div />,
    });
  }

  render() {
    const {items, loadedFirstPage} = this.props.entryList;

    return (
      <div>
        {loadedFirstPage && this.renderItems(items)}
        {this.renderNextPageLoading()}
      </div>
    );
  }
}

export default Playlist;
